### ISSUE TITLE
chef <analyze> capture node <name> (From Cache)

### ISSUE THREAD

**Issue by jonsmorrow** [chef/chef-workstation#1017]
#### Story
As an IT Operator
I want to capture the current state of a node into a local kitchen
So that I can begin testing changes

#### Description
This story is about the first pass of getting the customer a local environment where they can test changes. For this pass I think we could get everything we need from the nodes chef cache, or from querying the cookbook state from the Chef Server.

#### Questions
1. Can we suggest a similar platform or ask for an image (docs/PS could help get one)
1. Operators may not have access to a specific node in an enterprise environment. In this case it is easier to get information from the Chef Server rather than the node.
1. Does the node cache even include the environment and role information separated out, or has it already been flattened?

#### Acceptance Criteria
1. Command exists to capture snapshot of chef repo. This would be a mono-repo that includes all cookbooks needed to converge the chef-client on the node-in-test.
  1. This will need to include cookbooks, environments, roles, etc. - everything required to successfully converge the chef node
2. User can run kitchen converge with the version of chef on a similar platform to the current node
  1. This converge will leverage the local chef repo to ensure the test node mirrors the real node.
1. Users have all the information they need locally to start constructing a policyfile except the cookbook sources. EG, roles are not supported in a policyfile but now the user has all the information to translate their role usage into policyfile usage.

**Comment by jonsmorrow** [comment]
The converge probably wont be successful at the completion of the is card.

**Comment by jonsmorrow** [comment]
This can also have broad constraints to get to a minimal working thing.
It's totally ok to say this only works on nodes that the user has ssh access to or pretty much anything else as long as the team understands and agrees.

**Comment by jonsmorrow** [comment]
This card can be read as: Given a node what is the minimum we can do to get to a local kitchen converge. From that we'll figure out next steps towards the bigger vision.

**Comment by marcparadise** [comment]
Some notes from digging further into this below: 

A node's cache (/var/chef/cache) provides only cookbooks.  node
state/json/attribute  info is not captured in cache - it's
only sent to the server.

I started down the path of issuing the same request to
/environments/env/cookbook_versions that a client would issue to receive its
complete set of cookbook files/metadata.  this worked, but after comparing the
results to the node data, it turned  out to be unnecessary - the same info is
already in the node object, along with the other bits we need: 

 * roles
 * expanded_run_list (as determined by client at last run)
 * policy/group
 * cookbooks & versions that we need to download
 * separated attributes: override, default, automatic (remainder assemble at
   run-time, and automatic gets replaced)

Given this,  we have enough information to create a local chef repo that
contains :
  * the environment object
  * role object(s)
  * the node object
  * the cookbooks at the version required

Since the only data we can get from the node itself is a copy of the cookbooks 
it used at last run, I recommend that we proceed with the approach 
of reconstituting the repository locally using data from chef-server now instead
of trying to grab the node's cache.

**Comment by jonsmorrow** [comment]
@marcparadise Sounds good. Thanks for the investigation. What are the cases where we don't have what is needed on the chef server? Policyfile? or only effortless?

**Comment by marcparadise** [comment]
I will confirm, but it should be only effortless where the server isn't in the loop at all.

**Comment by marcparadise** [comment]
Confirmed that we still get the info we need when using policyfiles with Chef Server. The policy and group are captured to the node, as well as the complete list of cookbooks.
