### ISSUE TITLE
[SPIKE] Investigate existing Rollout metadata fetcher

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1326]
## Acceptance Criteria

1. Understanding of existing tool's capabilities to fetch required metadata
1. Gap analysis of existing tool to the desired tool (EG, "its missing auth") reported as comment on this card
1. Document in the Epic the pros/cons of an external tool vs updating `chef push` tooling
1. Proposal for where we could add this functionality into Chef Workstation (EG, "add it to the main-chef-wrapper")
1. Document any library dependencies needed

**Comment by tyler-ball** [comment]
That last acceptance criteria might be too much for a spike card. I'm trying to answer the question "do we need to write a library to interface with Automate?" or if that is already written, how do we add those dependencies to the Chef Workstation project?

**Comment by marcparadise** [comment]
> 1. Understanding of existing tool's capabilities to fetch required metadata

The existing WIP tool has two subcommands: 

1. gen-config: generates a repository configuration. I was not able to get this working because the endpoint isn't yet mapped in the WIP PR and so the command isn't able to verify the automate config before proceeding; but it looks like it writes config to `.automate_collector.toml`

 If `--private` is specified, the file written is `automate_collector_private.toml` and it is also added to the local .gitignore. 
The config file contains entries for url, token, TLS, and if  `--private` isn't given, The 'TestURL' used  to validate the service from `gen-config`. 
 
2. descrbe: generates a rollout description and outputs it as json.  Sample output: 
```
file/$ chef-automate-collect describe Policyfile.lock.json
{
  "policy_name": "example-application-service",
  "policy_revision_id": "502c3157a3cd92f1ab1ed073e5536b8a160028c56c8c848a89b889823f1d0105",
  "description": "",
  "scm_type": "GIT",
  "scm_web_type": "UNKNOWN_SCM_WEB",
  "policy_scm_url": "origin",
  "policy_scm_web_url": "",
  "policy_scm_commit": "ba0681a1a18d067449c7c3165acf31bfafe95b53",
  "policy_scm_commit_message": "added locl",
  "scm_author_name": "Marc A. Paradise",
  "scm_author_email": "marc.paradise@gmail.com",
  "ci_job_url": "https;//chef.ci/1",
  "ci_job_id": "1010"
}
``` 
Data seems gathered froma combination of environment variables (ci info), policyfile lock (name, revision), git CLI (scm fields)

> 4.  Document any library dependencies needed

There are no dependencies needed if we use the standalone binary `chef-automate-collect`.

**Comment by marcparadise** [comment]
>2. Gap analysis of existing tool to the desired tool (EG, "its missing auth") reported as comment on this card

This WIP tooling can currently configure a repository to support submitting Rollout metadata. This includes URL and auth, and it verifies auth on behalf of the user. 

It also emits Rollout metadata in json to stdout. 

It does not yet post the gathered metadata to Automate, and it does not provide for the `description` metadata field.

**Comment by marcparadise** [comment]
The command and usage instructions are also now available here: 

https://github.com/chef/automate/pull/4032

**Comment by tyler-ball** [comment]
Got this linked to the Epic so we can use it for future card writing - thank you Marc!
