### ISSUE TITLE
Fix automatic publishing of Homebrew PR on release

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#1330]
## Description

We currently have our Homebrew publishing [commented](https://github.com/chef/chef-workstation/pull/1239) out. We want to uncomment that and get it working.

During the course of implementing https://github.com/chef/chef-workstation/pull/1193 we ran into two issues:
1. If we use the expeditor builder, it does not have `brew` installed and we cannot perform the `brew cask style`/`brew cask audit` commands that Homebrew wants completed before opening a PR. 
2. If we use a Anka or MacOS docker image, it does not have access to the Vault tokens we need (Github), nor does it have the `open_pull_request` function defined.

My proposal to install the [Homebrew source](https://github.com/Homebrew/brew/tree/master/Library/Homebrew) because it is written in Ruby and then execute the two commands we need (`brew cask style` and `brew cask audit`).

**Comment by marcparadise** [comment]
On the Anka image, we do have access to the tokens (that has all been fixed/updated in the PR 1193 that you linked - that PR should probably get used as-is, since it's in good shape. 

 Basically everything is working as written in 1193 - style/audit is running, we can get to the tokens - but the PR API request itself fails - even though it's a correct request, with the correct token.  The error message we get in response is not informative. 

 I got the same results when attempting to directly open a PR with the same token. 

I think it's because the PR opens against the upstream repository.   We will probably need to work with releng to take this over the finish line, or possibly raise an issue with Github support.
