### ISSUE TITLE
no need to type winrm://

### ISSUE THREAD

**Issue by spuder** [chef/chef-workstation#178]
It would be nice if I didn't have to type `winrm://` in front of every server I want to connect to. 

Possible solutions

1. Add a `--winrm` parameter
2. Let me default to winrm in a config file (useful if I have more windows than linux hosts)
3. Auto detect the remote host os type if not specified

**Comment by jonsmorrow** [comment]
We talked about auto detect and thought it could lead to a less responsive experience. Our thought was what is the difference between not responding to ssh because the target is a windows host and just a slow or dropped connection. We'll totally do the flag and config override for default though and might revisit if we can do auto detect in a sane manner.
