### ISSUE TITLE
Configuration values are not respected when defaults are used in options

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-workstation#180]
## Description
When a custom configuration value is defined in config.toml, and the CLI option sets a default value to the configuration value, the customized default value is ignored. 

## Chef Workstation Version
0.1.120

## Platform Version
n/a 

## Replication Case
1. Set config option `connection.winrm.ssl` to `true`
2. run chef-run -h
3. output will contain a default cookbook repo path other than the provide value. 

## Client Output
```
grep ssl ~/.chef-workstation/config.toml
ssl=true
```
`chef-run -h`
-- snip
```
    -s, --[no-]ssl                     Use SSL for WinRM. Current default: false
```

**Comment by tyler-ball** [comment]
I'm not sure this is going to be possible.

The reason it does not work now is that we evaluate the mixlib-cli options at class loading time, but the config file is not loaded until the `setup_cli` method is called. This means the help text description is generated before we read the config file.

If we want to change that, we would need to load the config file before parsing any of the mixlib-cli options. I think this could be done? But we would have to parse the ARGV ourselves. Or maybe we can figure out a way to load the mixlib-cli options after the class has been initialized?

Either way we do it, we need to load the config file into the `ChefRun::Config` object before we parse the options. But one of the options specifies the `--config-path`, so we would need to manually read that from the ARGVs ourselves if we want to load the config before generating the options descriptions.

**Comment by tyler-ball** [comment]
I ran into another issue that is kind of the inverse of this.

If a user sets `--no-ssl` on the command line, but the default value is `ssl=true` we never persist that overridden value (`false`) anywhere. Everything works today because we pass the `config` object (lower case `c`, refers to the values we pulled from the parsed command line options) to the classes we need it.

But if a user later references the global `ChefRun::Config.connection.winrm.ssl` it will continue to return the default value (`true`) instead of the overridden value (`false`).

I think we could fix this by doing `ChefRun::Config.merge!(config)` to persist the CLI options back into the config global. But then we are really maintaining two different copies of config - the `config` hash and the `ChefRun::Config` global.

I think I would like to have a conversation with you @marcparadise where we decide if we can fix all of these config related issues at once. None of them seem very big and I think they overlap a lot of the same space.
