### ISSUE TITLE
Windows Installs are partially broken

### ISSUE THREAD

**Issue by johnmccrae** [chef/chef-workstation#2001]
## Description
After installing Chef Workstation and running any code that relies on PowerShell you'll get an error about a missing chef.powershell.wrapper.dll. During your investigation you'll note that the file and all it's related friends are missing from C:\opscode\chef-workstation\embedded\bin. You'll need to copy pretty much everything from an \AMD64 folder down below that path to make it start working.

Then you'll get frustrated and try to uninstall Chef-Workstation only to discover there is no uninstall registered with Windows. So now, you'll need to find a way to manually remove that version (or later versions). The MSI doesn't offer an uninstall feature either. 

## Chef Workstation Version
21.4.365 and later

## Platform Version
Windows 10

**Comment by marcparadise** [comment]
Note that these files are included in the chef gem.  We will need to include them in an accessible location (like chef-workstation/embedded/bin/modules) in the Workstation package in a similar way that the `chef` omnibus package does [1]. 

We should also look at the workstation `source.wxs.erb` file and compare it to what `chef-infra` does for `Chef.PowerShell` related components.  Some changes may be needed here to get PowerShell to be able to find the wrapper in `bin/modules` instead of requiring us to put it directly into bin or embedded/bin. 


[1] https://github.com/chef/omnibus-software/blob/6b77f49eedf208b3f10a71e5968df644d91450f3/config/software/chef.rb#L85-L89

**Comment by tas50** [comment]
Fixed
