### ISSUE TITLE
Dockerfile sets PATH incorrectly

### ISSUE THREAD

**Issue by ls-brentsmith** [chef/chef-workstation#564]
## Description
Dockerfile sets PATH incorrectly.
https://github.com/chef/chef-workstation/blob/60f5fb55dbbf2e2db38e9b30325f19665a4b6765/Dockerfile#L9 should prepend ` /opt/chef-workstation/ `  not ` /opt/chefworkstation/ ` 

Additionally, /root/.chefdk does not exist and should probably be removed.

##  Chef Workstation Version
tested 3 versions
Chef Workstation version: 0.10.6 (chef/chef-workstation:current)
Chef Workstation version: 0.9.42 (chef/chef-workstation:latest)
Chef Workstation version: 0.10.14 (chef/chef-workstation:0.10.14) 
Chef Workstation version: 0.9.42 (master Dockerfile)

## Platform Version
(Docker)
```
root@9c98817ce9a1:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by tyler-ball** [comment]
Hey @ls-brentsmith - thanks for filing this issue. Got two questions:

1) Are you using the Chef Workstation docker image or did you just stumble across this issue?
2) Would you want to attempt a PR to fix this? I think you're right that the change is `chefworkstation` -> `chef-workstation`. The `/root/.chefdk` folder should stay in the path because if users add any gems to the bundle (`chef gem install`) they will be installed to that folder. We want to change some of that functionality in the future but for now it is okay to leave that in the path.

**Comment by ls-brentsmith** [comment]
1) I'm attempting to use the CW image (and/or build it from master.)
2) Sure.  I'm fine with the ` chef gem install ` rationale, although I struggle to see the utility there inside the container :) 

I'll have a PR up shortly.
