### ISSUE TITLE
Can't upgrade gems inside bundle

### ISSUE THREAD

**Issue by scalp42** [chef/chef-workstation#967]
## Description
When installing a new gem, it doesn't get picked up by `chef exec`:

```
$> chef exec rubocop -v
0.75.1

$> chef exec gem install rubocop -v 0.8.0
Fetching rubocop-0.8.0.gem
Successfully installed rubocop-0.8.0
1 gem installed

$> chef exec gem list | grep rubocop
rubocop (0.75.1, 0.8.0)

$> chef exec rubocop -v
0.75.1

$> chef exec gem uninstall rubocop -aIx -V --backtrace
Successfully uninstalled rubocop-0.8.0

$> chef exec rubocop -v
0.75.1
```

Even if you uninstall all the gems, it seems that it won't pick up the "default" rubocop version `0.75.1` in this example.

We're not sure how to upgrade the underlying gems.

## Chef Workstation Version
```
Chef Workstation version: 0.13.35
Chef Infra Client version: 15.6.10
Chef InSpec version: 4.18.39
Chef CLI version: 2.0.0
Test Kitchen version: 2.3.4
Cookstyle version: 5.16.11
```

## Platform Version
macOS `10.14.6`

**Comment by jonsmorrow** [comment]
Thank you for filling an issue. This is by design. In Workstation and later version of DK we made a deliberate decision to ship a locked set of dependencies because many users were having trouble after upgrading. We have currently have an issue in our backlog to upgrade rubo cop. We'll link to this issue showing you are requesting that, but we likely will not re-enable user updating of included gems.

**Comment by jonsmorrow** [comment]
https://github.com/chef/cookstyle/pull/479

**Comment by scalp42** [comment]
@jonsmorrow I understand, we'll have to patch it on our end. Can you give us any pointers in the code to where we could modify this behavior?
